apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: openshift-tasks
  name: openshift-tasks
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: openshift-tasks:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/wkulhanek/openshift-tasks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jboss-eap70-openshift:1.6
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 6ZpOAsYCA-4NrGa4skh0
    type: GitHub
  - generic:
      secret: zCWmOgzuJnXlR8vVxFSx
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
